sudo: required
language: generic
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work
stages:
  - prepare cache
  - test
jobs:
  include:
  - stage: prepare cache
    script: true
  - stage: test
    script: ./ci/travis_test_myelin.sh
