sudo: false
language: c
cache:
  directories:
  - $HOME/.stack
  - $HOME/.local
  - $HOME/.stack-work-cache
  apt: true
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libblas-dev liblapack-dev
- if [ ! -e ~/.local/bin/stack ]; then mkdir -p ~/.local/bin; travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; fi
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
    '?')]"
- stack +RTS -N2 -RTS --version
script:
- travis_wait stack --no-terminal --skip-ghc-check test
