sudo: required
language: generic
services:
  - docker
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work
stages:
  - prepare cache
  - test
  - docker
jobs:
  include:
  - stage: prepare cache
    script: true
  - stage: test
    script: ./ci/travis/test_myelin.sh
  - stage: docker
    script: ./ci/travis/build_image.sh nest 2.14.0
  # Add concurrent builds for other targets within the same stage
env:
  global:
  - secure: me52WpSuOeZEzCATPUms9+1GcbupcFCI0cp/7PpDhQccOJX7u9qlBa7QvDxJvK0PPlOaKhEC3fL1MHs0pvSj8hC/tdHtdzhfP8sFjgjKZ8LWO8GLQjE19t0fesWrtQCC99QO72/RkJi+V3dXfit06myyhuZTi7JUfLqVubEX2GRyz+bvpO2u1cXLGcz+dkzldJyVjesV2a0tz5KSXbRre+wjNvmqQHF4UeUr+TddxttqxhvCyqe1xywsAwE0PLbxY80KHulovAobYwfNVnLBfun3UUQszbyJO1Sm1Ehwr1hv8V1TECwvCJhQzMdrFnDXD5Ekkt4BctAwkUHgzYpFzCHCd//Hj+RloS634E5/5h8OoHE+waVrljxicEh2h8JKJ+OSDxcVg6RDUozt+VylBdixFtr4GSnbn3BuWDxOIDUD2p3ezV9MbyReCjC3fTnYhkoiC5SzoqqdWpvAaLSy20daVqqqQH677EDeXZe9IbQs1Huk3ATkStH+H4mwZVcQ4MgX2TtQ8z3v0Z0mLqOv8RHkEiBQxHBCc+ieCU9obomMJKVRG6cTt8Yh9kQl3pEiiARy+jy9RtMRYzDOP8is2VC+YL0pvblhQeGQaCQmKpUbU25KeRjPHHw9XWvvFhU6QgE6uB0yQBsO2a4LAQI3acrA0eBUkLOwm3h8nx+krlA=
  - secure: QlBPY2d2VLv6gO5SMo9kYoDEIpE4cV5sdiiz46dWxjn5Xg3lJX/mPaFo0qRWEUxeYqekIFvDzK9U4laB7gxWZsQfU/gOkV1XYAQRFcdpLJLvnsB7SJNsnbCKTgqs/Kv01GuBeHIphqhk4WMXdTnXb+cHvcNXCwonqTV4qEULz9SmZCg3Y/P4tOOPHBhiubv1tGHugSJ5taKEZA6WN1rVUURew+XUY9vbQ/94HGoualmXUUenZ2Jh3Ln5JtX0g2VQPrdcUEtDYnwUQCXbPgP3LxpduIcoP9xZr+yrvgIKMqNqlKdMwUiPJlibkfDGCCNdfsct8otTxzidv/PywjS5mIXPTvn1xKYYOxZN2dF/Y+r+X1GGwL18WS5OgVuqcT/qS+Zo4ZwdjSjWh3xC+OIIFEqIEBfK/Vs0RW3AagtcpJLYwYiuT86pFz0ACFFk7tvlIUBjxaUEmPQcpnrSQt0/CUvTnodR15KHihR6/2nSeY0NaxrMrgmUbPSmfalSG/Du9w6Pc4eMb0/RguWCfY+W3QTQSN50Ici27gLpiWEUZj7EtBAHz0jjXa9rcACn3d5LmyrxSL58JE7pF4R9opR+FRJzg2ERhxhEiCjAK8e7GSe0jAIHM8SR6H90tpwahcGhO+g1HUsLJWoTtSDMEYhKLq5Lq7/p2KsLWOMM8PhQZvs=
