name:                myelin
version:             0.1.0.0
github:              "cpehle/myelin"
license:             BSD3
author:              "Christian Pehle"
maintainer:          "christian.pehle@kip.uni-heidelberg.de"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/cpehle/myelin#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- bytestring
- proto-lens-protoc
- proto-lens
- transformers
- aeson
- text
- graphviz
- transformers
- aeson-pretty
- bytestring

library:
  source-dirs: src

executables:
  myelin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myelin

tests:
  myelin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myelin
